# Test playbook for Ansible role bertvv.wordpress
---

- hosts: all
  become: true
  vars:
    wordpress_database_host: 172.17.0.2
    wordpress_database: wordpress_db
    wordpress_user: wordpress_usr
    wordpress_password: ywIapecJalg6
    wordpress_plugins:
      - name: wp-super-cache
        version: 1.6.4
      - name: jetpack
        version: '6.5'
      - name: lipsum
    wordpress_themes:
      - name: xcel
        version: 1.2.01
  roles:
    - bertvv.httpd
    - role_under_test
