# roles/wordpress/tasks/config.yml
# Configures Wordpress
---

- name: Apache config file for Wordpress
  copy:
    src=wordpress.conf
    dest=/etc/httpd/conf.d/wordpress.conf
    owner=root
    group=root
    mode=0644
    setype=httpd_config_t
  notify: restart httpd
  tags: wordpress

- name: Get Salts
  command: curl https://api.wordpress.org/secret-key/1.1/salt/
  register: wordpress_salt
  tags: wordpress

- name: Wordpress config file
  template:
    src=wp-config.php.j2
    dest=/etc/wordpress/wp-config.php
    owner=root
    group=apache
    mode=0640
    setype=etc_t
  notify: restart httpd
  tags: wordpress

