# roles/wordpress/tasks/install.yml
---

- name: Ensure repository is installed
  package:
    name: "{{ item }}"
    state: installed
  with_items: "{{ wordpress_repository }}"
  tags: wordpress

- name: Install Wordpress
  package:
    name: "{{ item }}"
    state: installed
  with_items: "{{ wordpress_packages }}"
  tags: wordpress

