# roles/wordpress/tasks/main.yml
---

## Installation

- name: Ensure EPEL repository is installed
  yum:
    pkg: epel-release
    state: installed
  tags: wordpress

- name: Install Wordpress
  yum:
    pkg: "{{ item }}"
    state: installed
  with_items: wordpress_packages
  tags: wordpress

## Configuration

- name: Apache config file for Wordpress
  copy:
    src=wordpress.conf
    dest=/etc/httpd/conf.d/wordpress.conf
    owner=root
    group=root
    mode=0644
    setype=httpd_config_t
  notify: restart httpd
  tags: wordpress

- name: Get Salts
  command: curl https://api.wordpress.org/secret-key/1.1/salt/
  register: wordpress_salt
  tags: wordpress

- name: Wordpress config file
  template:
    src=wp-config.php.j2
    dest=/etc/wordpress/wp-config.php
    owner=root
    group=apache
    mode=0640
    setype=etc_t
  notify: restart httpd
  tags: wordpress

## Plugins - install without version number

- name: Download plugins
  get_url:
    url: "https://downloads.wordpress.org/plugin/{{ item.name }}{{ item.version }}.zip"
    dest: "/tmp/{{ item.name }}{{ item.version }}.zip"
  with_items: wordpress_plugins
  tags: wordpress
  when: item.version == ""

- name: Unpack plugins
  unarchive:
    src: "/tmp/{{ item.name }}{{ item.version }}.zip"
    dest: "{{ wordpress_plugin_directory }}"
    copy: false
  with_items: wordpress_plugins
  tags: wordpress
  when: item.version == ""
  
## Plugins - with version number

- name: Download plugins
  get_url:
    url: "https://downloads.wordpress.org/plugin/{{ item.name }}.{{ item.version }}.zip"
    dest: "/tmp/{{ item.name }}.{{ item.version }}.zip"
  with_items: wordpress_plugins
  tags: wordpress
  when: item.version != ""

- name: Unpack plugins
  unarchive:
    src: "/tmp/{{ item.name }}.{{ item.version }}.zip"
    dest: "{{ wordpress_plugin_directory }}"
    copy: false
  with_items: wordpress_plugins
  tags: wordpress

## Themes

- name: Download themes
  get_url:
    url: "https://downloads.wordpress.org/theme/{{ item.name }}.{{ item.version }}.zip"
    dest: "/tmp/{{ item.name }}.{{ item.version }}.zip"
  with_items: wordpress_themes
  tags: wordpress

- name: Unpack themes
  unarchive:
    src: "/tmp/{{ item.name }}.{{ item.version }}.zip"
    dest: "{{ wordpress_theme_directory }}"
    copy: false
  with_items: wordpress_themes
  tags: wordpress

